"""
Compute Friedman + post hoc statistics for Act 10 real-world comparison.

Datasets:
- Suzuki
- ADA coatings
- GDSC CRC5
- SDL5

Algorithms (display slot):
- Novelty Aware EGBO
- EGBO
- qNEHVI

Inputs (generated by plot_realworld_posthoc_realworld_posthoc.py):
- realworld_posthoc_realworld_summary.csv
- realworld_posthoc_realworld_igd_summary.csv
- realworld_posthoc_realworld_final_hv.csv
- realworld_posthoc_realworld_final_igd.csv

Outputs:
- realworld_posthoc_friedman_dataset_level_hv.csv
- realworld_posthoc_friedman_dataset_level_igd.csv
- realworld_posthoc_pairwise_dataset_level_hv.csv
- realworld_posthoc_pairwise_dataset_level_igd.csv
- realworld_posthoc_friedman_trial_aligned_hv.csv
- realworld_posthoc_friedman_trial_aligned_igd.csv
- realworld_posthoc_pairwise_trial_aligned_hv.csv
- realworld_posthoc_pairwise_trial_aligned_igd.csv
- realworld_posthoc_friedman_posthoc_report.md
"""

from __future__ import annotations

from pathlib import Path
from itertools import combinations

import numpy as np
import pandas as pd
from scipy.stats import friedmanchisquare, rankdata, wilcoxon, f

HERE = Path(__file__).resolve().parent

ALGO_ORDER = ["Novelty Aware EGBO", "EGBO", "qNEHVI"]
DATASET_ORDER = ["Suzuki", "ADA coatings", "GDSC CRC5", "SDL5"]

# Nemenyi q_alpha for alpha=0.05, k=3, large-sample approximation (Demsar 2006 table)
NEMENYI_Q_ALPHA_05_K3 = 2.343


def _holm_adjust(pvals: list[float]) -> list[float]:
    """Holm-Bonferroni adjusted p-values (step-down)."""
    m = len(pvals)
    order = np.argsort(pvals)
    adjusted = np.empty(m, dtype=float)
    prev = 0.0
    for i, idx in enumerate(order):
        factor = m - i
        val = min(1.0, pvals[idx] * factor)
        val = max(val, prev)
        adjusted[idx] = val
        prev = val
    return adjusted.tolist()


def _pairwise_wilcoxon(block_algo: pd.DataFrame, metric_name: str, higher_is_better: bool) -> pd.DataFrame:
    rows = []
    for a, b in combinations(ALGO_ORDER, 2):
        x = block_algo[a].to_numpy(dtype=float)
        y = block_algo[b].to_numpy(dtype=float)
        d = x - y
        nz = d[np.abs(d) > 1e-12]

        if len(nz) == 0:
            p = 1.0
            stat = 0.0
            rbc = 0.0
        else:
            # two-sided Wilcoxon signed-rank
            res = wilcoxon(x, y, zero_method="wilcox", alternative="two-sided", mode="auto")
            stat = float(res.statistic)
            p = float(res.pvalue)

            # rank-biserial correlation (paired):
            # RBC = (W+ - W-) / (W+ + W-)
            ranks = rankdata(np.abs(nz))
            w_pos = float(np.sum(ranks[nz > 0]))
            w_neg = float(np.sum(ranks[nz < 0]))
            denom = w_pos + w_neg
            rbc = 0.0 if denom == 0 else (w_pos - w_neg) / denom

        mean_a = float(np.mean(x))
        mean_b = float(np.mean(y))
        median_diff = float(np.median(d))

        if higher_is_better:
            favored = a if mean_a > mean_b else b
        else:
            favored = a if mean_a < mean_b else b

        rows.append(
            {
                "metric": metric_name,
                "algo_a": a,
                "algo_b": b,
                "n_blocks": int(len(x)),
                "mean_a": mean_a,
                "mean_b": mean_b,
                "median_diff_a_minus_b": median_diff,
                "wilcoxon_W": stat,
                "p_value": p,
                "rank_biserial_corr": rbc,
                "favored_by_mean": favored,
            }
        )

    out = pd.DataFrame(rows)
    out["p_holm"] = _holm_adjust(out["p_value"].tolist())
    out["significant_0_05"] = out["p_holm"] < 0.05
    return out


def _friedman_from_block_algo(block_algo: pd.DataFrame, metric_name: str, higher_is_better: bool) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    block_algo: rows = blocks (datasets or dataset-trials), cols = algorithms in ALGO_ORDER
    """
    arr = [block_algo[a].to_numpy(dtype=float) for a in ALGO_ORDER]
    chi2, p = friedmanchisquare(*arr)

    n = block_algo.shape[0]  # blocks
    k = len(ALGO_ORDER)      # algorithms

    # Iman-Davenport F approximation
    ff = ((n - 1) * chi2) / (n * (k - 1) - chi2) if (n * (k - 1) - chi2) > 0 else np.nan
    ff_p = 1.0 - f.cdf(ff, k - 1, (k - 1) * (n - 1)) if np.isfinite(ff) else np.nan

    # Ranks per block (best rank=1)
    # HV: higher better -> rank descending
    # IGD: lower better -> rank ascending
    ranks = []
    for _, row in block_algo.iterrows():
        vals = row[ALGO_ORDER].to_numpy(dtype=float)
        if higher_is_better:
            rr = rankdata(-vals, method="average")
        else:
            rr = rankdata(vals, method="average")
        ranks.append(rr)
    ranks = np.vstack(ranks)
    avg_ranks = np.mean(ranks, axis=0)

    # Nemenyi critical difference
    cd = NEMENYI_Q_ALPHA_05_K3 * np.sqrt(k * (k + 1) / (6.0 * n))

    friedman_row = pd.DataFrame(
        [
            {
                "metric": metric_name,
                "n_blocks": int(n),
                "k_algorithms": int(k),
                "friedman_chi2": float(chi2),
                "friedman_p": float(p),
                "iman_davenport_F": float(ff),
                "iman_davenport_p": float(ff_p),
                "nemenyi_cd_alpha_0_05": float(cd),
            }
        ]
    )

    rank_rows = []
    for i, a in enumerate(ALGO_ORDER):
        rank_rows.append(
            {
                "metric": metric_name,
                "algorithm": a,
                "avg_rank": float(avg_ranks[i]),
            }
        )

    # pairwise rank differences against CD
    for a, b in combinations(ALGO_ORDER, 2):
        ra = float(avg_ranks[ALGO_ORDER.index(a)])
        rb = float(avg_ranks[ALGO_ORDER.index(b)])
        rank_rows.append(
            {
                "metric": metric_name,
                "algorithm": f"{a} vs {b}",
                "avg_rank": abs(ra - rb),
                "notes": f"abs rank diff; >CD? {abs(ra-rb) > cd}",
            }
        )

    return friedman_row, pd.DataFrame(rank_rows)


def _prepare_dataset_level_hv() -> pd.DataFrame:
    s = pd.read_csv(HERE / "realworld_posthoc_realworld_summary.csv")
    s = s[s["algorithm"].isin(ALGO_ORDER)].copy()
    s = s[s["problem"].isin(DATASET_ORDER)].copy()
    piv = s.pivot(index="problem", columns="algorithm", values="final_hv_mean").reindex(DATASET_ORDER)
    piv = piv[ALGO_ORDER]
    return piv


def _prepare_dataset_level_igd() -> pd.DataFrame:
    s = pd.read_csv(HERE / "realworld_posthoc_realworld_igd_summary.csv")
    s = s[s["algorithm"].isin(ALGO_ORDER)].copy()
    s = s[s["problem"].isin(DATASET_ORDER)].copy()
    piv = s.pivot(index="problem", columns="algorithm", values="final_igd_mean").reindex(DATASET_ORDER)
    piv = piv[ALGO_ORDER]
    return piv


def _prepare_trial_aligned(path: Path, value_col: str) -> pd.DataFrame:
    d = pd.read_csv(path)
    d = d[d["algorithm"].isin(ALGO_ORDER)].copy()
    d = d[d["problem"].isin(DATASET_ORDER)].copy()

    d["block"] = d["problem"].astype(str) + "::trial_" + d["trial"].astype(int).astype(str)
    piv = d.pivot(index="block", columns="algorithm", values=value_col)

    # Keep only complete blocks where all algorithms exist
    piv = piv.dropna(axis=0, how="any")
    piv = piv[ALGO_ORDER]
    return piv


def _write_report(
    hv_ds_f: pd.DataFrame,
    hv_ds_r: pd.DataFrame,
    hv_ds_pw: pd.DataFrame,
    igd_ds_f: pd.DataFrame,
    igd_ds_r: pd.DataFrame,
    igd_ds_pw: pd.DataFrame,
    hv_tr_f: pd.DataFrame,
    hv_tr_r: pd.DataFrame,
    hv_tr_pw: pd.DataFrame,
    igd_tr_f: pd.DataFrame,
    igd_tr_r: pd.DataFrame,
    igd_tr_pw: pd.DataFrame,
) -> None:
    lines = []
    lines.append("# Act 10 — Friedman and post hoc statistics\n")
    lines.append("Algorithms: Novelty Aware EGBO, EGBO, qNEHVI")
    lines.append("Datasets: Suzuki, ADA coatings, GDSC CRC5, SDL5\n")

    def add_section(title: str, fr: pd.DataFrame, ranks: pd.DataFrame, pw: pd.DataFrame) -> None:
        lines.append(f"## {title}\n")
        row = fr.iloc[0]
        lines.append(
            "- Friedman: "
            f"$\\chi^2={row['friedman_chi2']:.4f}$, "
            f"$p={row['friedman_p']:.6f}$"
        )
        lines.append(
            "- Iman–Davenport: "
            f"$F={row['iman_davenport_F']:.4f}$, "
            f"$p={row['iman_davenport_p']:.6f}$"
        )
        lines.append(f"- Nemenyi CD ($\\alpha=0.05$): {row['nemenyi_cd_alpha_0_05']:.4f}")

        rr = ranks[ranks["algorithm"].isin(ALGO_ORDER)].sort_values("avg_rank")
        lines.append("- Average ranks (best = lowest):")
        for _, r in rr.iterrows():
            lines.append(f"  - {r['algorithm']}: {r['avg_rank']:.4f}")

        lines.append("- Pairwise Wilcoxon (Holm-adjusted):")
        for _, r in pw.iterrows():
            sig = "yes" if bool(r["significant_0_05"]) else "no"
            lines.append(
                f"  - {r['algo_a']} vs {r['algo_b']}: "
                f"p={r['p_value']:.6f}, p_holm={r['p_holm']:.6f}, "
                f"RBC={r['rank_biserial_corr']:.4f}, sig={sig}, favored={r['favored_by_mean']}"
            )
        lines.append("")

    add_section("Dataset-level HV means (4 blocks)", hv_ds_f, hv_ds_r, hv_ds_pw)
    add_section("Dataset-level IGD means (4 blocks)", igd_ds_f, igd_ds_r, igd_ds_pw)
    add_section("Trial-aligned HV (4 datasets × 10 trials = 40 blocks)", hv_tr_f, hv_tr_r, hv_tr_pw)
    add_section("Trial-aligned IGD (4 datasets × 10 trials = 40 blocks)", igd_tr_f, igd_tr_r, igd_tr_pw)

    (HERE / "realworld_posthoc_friedman_posthoc_report.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    # Dataset-level (4 blocks)
    hv_ds = _prepare_dataset_level_hv()
    igd_ds = _prepare_dataset_level_igd()

    hv_ds_f, hv_ds_r = _friedman_from_block_algo(hv_ds, "HV_dataset_level", higher_is_better=True)
    igd_ds_f, igd_ds_r = _friedman_from_block_algo(igd_ds, "IGD_dataset_level", higher_is_better=False)

    hv_ds_pw = _pairwise_wilcoxon(hv_ds, "HV_dataset_level", higher_is_better=True)
    igd_ds_pw = _pairwise_wilcoxon(igd_ds, "IGD_dataset_level", higher_is_better=False)

    hv_ds_f.to_csv(HERE / "realworld_posthoc_friedman_dataset_level_hv.csv", index=False)
    hv_ds_r.to_csv(HERE / "realworld_posthoc_friedman_dataset_level_hv_ranks.csv", index=False)
    hv_ds_pw.to_csv(HERE / "realworld_posthoc_pairwise_dataset_level_hv.csv", index=False)

    igd_ds_f.to_csv(HERE / "realworld_posthoc_friedman_dataset_level_igd.csv", index=False)
    igd_ds_r.to_csv(HERE / "realworld_posthoc_friedman_dataset_level_igd_ranks.csv", index=False)
    igd_ds_pw.to_csv(HERE / "realworld_posthoc_pairwise_dataset_level_igd.csv", index=False)

    # Trial-aligned sensitivity analysis (40 blocks)
    hv_tr = _prepare_trial_aligned(HERE / "realworld_posthoc_realworld_final_hv.csv", value_col="hv")
    igd_tr = _prepare_trial_aligned(HERE / "realworld_posthoc_realworld_final_igd.csv", value_col="final_igd")

    hv_tr_f, hv_tr_r = _friedman_from_block_algo(hv_tr, "HV_trial_aligned", higher_is_better=True)
    igd_tr_f, igd_tr_r = _friedman_from_block_algo(igd_tr, "IGD_trial_aligned", higher_is_better=False)

    hv_tr_pw = _pairwise_wilcoxon(hv_tr, "HV_trial_aligned", higher_is_better=True)
    igd_tr_pw = _pairwise_wilcoxon(igd_tr, "IGD_trial_aligned", higher_is_better=False)

    hv_tr_f.to_csv(HERE / "realworld_posthoc_friedman_trial_aligned_hv.csv", index=False)
    hv_tr_r.to_csv(HERE / "realworld_posthoc_friedman_trial_aligned_hv_ranks.csv", index=False)
    hv_tr_pw.to_csv(HERE / "realworld_posthoc_pairwise_trial_aligned_hv.csv", index=False)

    igd_tr_f.to_csv(HERE / "realworld_posthoc_friedman_trial_aligned_igd.csv", index=False)
    igd_tr_r.to_csv(HERE / "realworld_posthoc_friedman_trial_aligned_igd_ranks.csv", index=False)
    igd_tr_pw.to_csv(HERE / "realworld_posthoc_pairwise_trial_aligned_igd.csv", index=False)

    _write_report(
        hv_ds_f=hv_ds_f,
        hv_ds_r=hv_ds_r,
        hv_ds_pw=hv_ds_pw,
        igd_ds_f=igd_ds_f,
        igd_ds_r=igd_ds_r,
        igd_ds_pw=igd_ds_pw,
        hv_tr_f=hv_tr_f,
        hv_tr_r=hv_tr_r,
        hv_tr_pw=hv_tr_pw,
        igd_tr_f=igd_tr_f,
        igd_tr_r=igd_tr_r,
        igd_tr_pw=igd_tr_pw,
    )

    print("Done. Wrote Friedman/post hoc outputs in:")
    print(HERE)


if __name__ == "__main__":
    main()
